### ISSUE TITLE
Comment the codebase

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#102]
Aside from the config.js, the majority of the code base isn't commented. 

Please provide quality commenting within the code base.

**Comment by LindsayThomas** [comment]
Please add Comments to localized-strings.js

(other files have comments)

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas  We will add the comments in localized-strings.js in next release.

**Comment by LindsayThomas** [comment]
verified
