### ISSUE TITLE
2-D array height for each page inconsistent

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/briefing-book#108]
In the JSON there is a 2D array height for each page (BookConfigData.BookPages[2].height[n][m]).  We want to interpret the numbers in the height array to be the heights of the items on that particular page but then noticed that in some cases, the numer of elements in the "heights" array is not equal to the number of items on the corresponding page.  Also, there is a "height" attribute in some of the item nodes (e.g., ModuleConfigData.BookPages[2].139585254473501.height) and the two "heights" are not always equal.  It is not clear which "height" should be honored.

**Comment by LindsayThomas** [comment]
@nfeuerstein  Could you please verify that the latest code drop fixes this issue?
Please verify using branch :https://github.com/Esri/briefing-book/tree/develop_2.0
Also, please note the configuration file has some new options. You will now need to define, if you are searching all of AGOL, just an organization or only a group.

**Comment by nfeuerstein** [comment]
Verified as fixed.  Number of height arrays now matches the number of items on a page.
