### ISSUE TITLE
The "width" attribute is missing values in some items.

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/briefing-book#109]
In some items the "width" attribute is empty.

**Comment by LindsayThomas** [comment]
@nfeuerstein  Could you please verify that the latest code drop fixes this issue?
Please verify using branch :https://github.com/Esri/briefing-book/tree/develop_2.0
Also, please note the configuration file has some new options. You will now need to define, if you are searching all of AGOL, just an organization or only a group.

**Comment by nfeuerstein** [comment]
@LindsayThomas - verified all height attributes were complete, but width attributes were removed.  Was this as intended?

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam It appears that all the "width attributes" were removed from the JSON. Was this because the width attribute wasn't required?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas @nfeuerstein 
That is correct. The width attribute is removed because it is not required. Width is dynamically assigned to modules based on width of its container.

**Comment by nfeuerstein** [comment]
@CTLocalGovTeam @LindsayThomas - that satisfies our need then.  If the width attribute is not present, then the native app won't search for it.
