### ISSUE TITLE
Book Contents page mandatory or optional

### ISSUE THREAD

**Issue by swang2013** [Esri/briefing-book#111]
The app allows users to create books with or without a contents page. When a book has no contents page, "Contents" still shows up when clicking on the "Contents" button at the top of the screen. And if one clicks on "Contents", nothing happens. 

Must each book have a Contents page? If every book must have a contents page, then users should not be allowed to create/save books that don't have one. But if it's optional, then when a book doesn't have one it should not show up in the table of contents. 

![image](https://cloud.githubusercontent.com/assets/4663390/2962783/0bca3768-dad4-11e3-8ffb-39f5ce12063c.png)

**Comment by LindsayThomas** [comment]
In the new version of BB, If Content Page is not implemented then it does show up in the pop out side panel. As expected. 

@swang2013 @nfeuerstein Does this design change satisfy your required for the native app.
Could you please verify that the latest code drop fixes this issue?
Please verify using branch :https://github.com/Esri/briefing-book/tree/develop_2.0
Also, please note the configuration file has some new options. You will now need to define, if you are searchin all of AGOL, just an organization or only a group.

**Comment by nfeuerstein** [comment]
@LindsayThomas - verified that the change satisfy requirements for native app.
