### ISSUE TITLE
Empty arrays in JSON

### ISSUE THREAD

**Issue by swang2013** [Esri/briefing-book#112]
Suppose there are 2 items on a page, but only one is populated, the JSON would show the populated item and an empty array. Should that empty array not be there at all? 

      "content": [
        [
          [],   
          "139993245373310"
        ]
      ],

**Comment by LindsayThomas** [comment]
@swang2013 Could you please verify that the latest code drop fixes this issue?
Please verify using branch :https://github.com/Esri/briefing-book/tree/develop_2.0
Also, please note the configuration file has some new options. You will now need to define, if you are searchin all of AGOL, just an organization or only a group.

**Comment by nfeuerstein** [comment]
@LindsayThomas - verified as fixed.
