### ISSUE TITLE
Use all lowercase folders, URL References etc. to support best practices.

### ISSUE THREAD

**Issue by rbernstein** [Esri/briefing-book#122]
You have to make sure this works in Tomcat, which is case sensitive.  You don't experience this with IIS but I have had to fix a bunch of stuff because of bad files names (e.g. images1.gif is not the same as images1.GIF to Tomcat).

**Comment by LindsayThomas** [comment]
LT- Testing Completed for  
FF View only on default TIL tests 

Note- alignment has changes slightly, meaning  books are scrolling in the new app but not the old.

**Comment by LindsayThomas** [comment]
@nfeuerstein Do you have anyone on your team who can verify that we are meeting this request?

**Comment by conklinbd** [comment]
Verified fixed.
