### ISSUE TITLE
localized the strings listed in the code in the description

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#138]
Sharing options – The text ‘Share’ comes from ‘widgets/shareBook/sharebook.js’. Please look for  line no 78 – btnShare = domConstruct.create("div", { "class": "esriSelectWebmapBtn", "innerHTML": "Share" }, btnContainer); 

	Page Ribbon – The text ‘Page’ is coming from ‘widgets/mapBookCollection/pageNavigation.js’. Please look for  line no 65 – domConstruct.create("div", { "class": "esriPageSliderDiv esriBookPage", "index": bookPageIndex + 2, "innerHTML": "Page " + (bookPageIndex + 1) }, listItem);

**Comment by LindsayThomas** [comment]
![screen shot 2015-02-19 at 3 05 20 pm](https://cloud.githubusercontent.com/assets/2379312/6274896/c19305fa-b848-11e4-96f6-cb0b425042f6.png)
![screen shot 2015-02-19 at 3 05 15 pm](https://cloud.githubusercontent.com/assets/2379312/6274902/c5a2f240-b848-11e4-8cca-912150c8a9be.png)

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas  We will provide this fix in next release.

**Comment by LindsayThomas** [comment]
verified
