### ISSUE TITLE
Flickr Widget is not working Briefing Book (released and current version) 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#150]
The Flickr Widget isn't working. Is it possible the API changed? I've used 2 different API Keys, including the cybertech provided APIKEY and username that has always worked. 
Repro steps
using configsearchtag "BriefingBookConfigItem" 
Go to Sample Public Book 1  
(Briefing Book page 4 of 4) 
Look at the Flickr Wigdet (it no longer displays the images.) 

(I can repro this issue using my APIKey and username). 

When I look in Fiddler I get the error message 

dojo.io.script.jsonp_dojoIoScript1._jsonpCallback({"stat":"fail", "code":95, "message":"SSL is required"})

I don't think we required SSL before.

Are you able to reproduce?

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Flickr is now pulling the photo stream of the API creator. It is not getting the photo stream from the defined URL

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas We will provide this fix in next release.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam 
I am unable get the flickr module to work. 
I have tried using the required parameters. 
username, APIkey, URL 

I tried using both the complete URL https://www.flickr.com/photos/esri/sets/72157648311130995 as well as just the alpha numeric value (72157648311130995)

Are you able to get flickr to work?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas We have configured [the app](http://203.199.47.84/briefingbook/v2.1/?bookId=b4fb45bf5ac142c294876eb749d65305). It is working with or without APIKey using username as 'esri' and provided URL (complete URL and just photosetid). 

Could you please provide more details on this?

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam I can now see it working. However, I don't think it is implemented correctly. 

Is the API hardcoded? I can now see photos without an API Key

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam based on the information on the call. 
Please remove the APIKEY (we want the app to use the default dojo apikey
For the string test that says "username" can we update it to say "Photo set username" (this should be in the NLS\localized.js) 

Also, could you please verify that using usernames\photosets other than Esri works?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas ,
We will remove the APIKEY parameter from flickr module settings. It will not be displayed in module settings dialog.

The text "Username" cannot be changed. In fact, all the labels currently displayed in the settings dialog e.g., URL, tags, row, column, etc., cannot be changed. These labels are actually being used to store/retrieve settings to render the module. This is also the case for other modules too.
An alternative we are thinking of is to display "Photo set username" as the default text in the text box in settings dialog. This default text will be configurable from NLS.

We have verified that using usernames/photosets other than Esri works.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam in reference too "These labels are actually being used to store/retrieve settings to render the module. This is also the case for other modules too." 

Does this mean that all the visible "text" in every module (Flickr, Video, Image, etc.)  is hardcoded to english and not in the NLS or config.js?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas, 
No. It does not mean all the visible "text" in all modules are hardcoded to english. To explain this clearly, please look at the following graphics that illustrate which ones are sourced from NLS.

----
### Map Module
![1mapcontrol](https://cloud.githubusercontent.com/assets/2959186/7470872/42f1758e-f33e-11e4-8c51-6c80032656c7.png)

----
### Text Module
![2text](https://cloud.githubusercontent.com/assets/2959186/7470882/4ec5b992-f33e-11e4-95f4-7e6abcb5f0d2.png)

----
### Video Module
![3video](https://cloud.githubusercontent.com/assets/2959186/7470887/5971c804-f33e-11e4-9791-b39b76e5a1f2.png)

----
### HTML Module
![4html](https://cloud.githubusercontent.com/assets/2959186/7470889/618e1394-f33e-11e4-8179-6d16d39f305e.png)

----
### Flickr Module
![5flickr](https://cloud.githubusercontent.com/assets/2959186/7470891/69f91df8-f33e-11e4-8759-2f02c065fb59.png)

----
### Image Module
![6 image](https://cloud.githubusercontent.com/assets/2959186/7470895/73d90d4c-f33e-11e4-97df-8ea5e46d7dbe.png)

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Thanks for the clarification. 

To summarize the display text that is stored in the config.js, is also a variable that the application is using? (therefore we can't change the text it because it is actually a variable name?) 

Assuming the above is true, then we need to update the application to have display texts in the NLS. The variables can remain in the config.js, however, the display text should be coming from elements in the NLS. 

Can we do that?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas, Yes we can do that.

We are thinking of two approaches.

#### Approach 1
Add NLS tags for all labels/variables displayed in modules as shown in screenshot below.

![image](https://cloud.githubusercontent.com/assets/2959186/7492392/51cf28f8-f415-11e4-9cd9-6eff635760cd.png)

#### Approach 2
The NLS file has grown in size. We can restructure the complete NLS file and make logical groupings of the NLS tags to enhance readability as in this screenshot.

![image](https://cloud.githubusercontent.com/assets/2959186/7492395/58f2dc10-f415-11e4-862d-6d8cd11e9c07.png)

Implementing approach 2 will need code changes throughout the app to rewire all NLS references. Whereas, implementing approach 1 will need minor code change.

Please let us know your preference.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Let's go ahead with Approach 1. 
Just to verify this change will happen for the following modules: image module, flickr module, HTML, Video, Map  ?     (Text isn't included because everything in in the NLS already)

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas That is correct. This change will happen in image, flickr, HTML, video and map modules only. Text module already has everything sourced from NLS.
Thanks for the confirmation, we will go ahead with implementation of approach 1.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Sounds good. Thank you.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas, 
Since, the labels will now be sourced from NLS, users can possibly configure lengthy labels while localizing this app. This may lead to potential positioning/formatting issues in the settings dialog UI for all modules.
We see two options to handle this. Please let us know your preference.

![image](https://cloud.githubusercontent.com/assets/2959186/7584829/f50ce1f2-f8bd-11e4-9e03-493760d9db4c.png)

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Option 1 please.

**Comment by LindsayThomas** [comment]
- [ ] Flickr API Key requirement is removed.

**Comment by LindsayThomas** [comment]
Verified NLS\ API removal and a variety of Configs
