### ISSUE TITLE
Large images are missing a close button, should be centered as well

### ISSUE THREAD

**Issue by jguard** [Esri/briefing-book#151]
Steps to reproduce:

1. Edit a Briefing Book page
2. Drag and drop an Image widget into the page
3. Reference URL example: http://upload.wikimedia.org/wikipedia/commons/c/cc/ESC_large_ISS022_ISS022-E-11387-edit_01.JPG
4. Save the changes, click on the image.
Notice that the "X" in the lower right hand corner disappears. 
5. Also, notice the image is not centered

Workaround: click anywhere outside of the image pop-up to return to the page.

See example here:

![noclosingbuttonlargepicture](https://cloud.githubusercontent.com/assets/7528583/4000503/48df30b6-295a-11e4-8bd1-3d7dd76b34bc.png)

**Comment by LindsayThomas** [comment]
Verified
