### ISSUE TITLE
Table of Contents page fonts/size

### ISSUE THREAD

**Issue by jguard** [Esri/briefing-book#152]
1. Changing the Briefing Book homepage title style/color/font does not reflect the changes in the Table of Contents.

#152 (originally in this issue broke out into two issues other issue now in #160)

See an example of both issues in the following screen shot:
![tableofcontents](https://cloud.githubusercontent.com/assets/7528583/4014637/b110f2e6-2a22-11e4-8f4c-54c51dbb2511.png)

(updates by LT)

**Comment by LindsayThomas** [comment]
Verified in sliding TOC and master TOC
