### ISSUE TITLE
Add Visual Cues in authoring mode to illustrate when the scrolling bar will appear on the tablet view of the applicaiton 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#159]
When designing the application in author mode on a desktop browser. It is difficult to determine when the the modules have a scroll bar appearing in the tablet version of the application. 

-Add Visual Cues in authoring mode to illustrate when the scrolling bar will appear on the tablet view of the application

**Comment by LindsayThomas** [comment]
lines appear at the bottom of the screen for Ipad\Android. Need to test if it functions with the tablet correctly. Stand up application on external web server.

**Comment by LindsayThomas** [comment]
Verified Device Name is configurable

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam 

I created a book
http://50.18.115.76/BriefingBookSpring/   Book Name (iPad retina 2048 x 1536) 

I ensured that I am above the iPad-3 2048X536 line. However, when I view it on a iPad with the iPad retina 2048 x 1536 display. I am missed contenting that I should be seeing.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
Although the Retina display has a resolution of 2048x1536, the screen resolution as far as CSS pixels is concerned is still 1024x768. Hence, we cannot add a visual cue at 2048x1536 in the configuration for retina displays, 1024x768 will work for retina displays too.

Please see a related discussion on stackoverflow that describes this http://stackoverflow.com/questions/25504947/why-does-media-query-targeting-1024x768-also-target-ipads-with-retina-display

You can also open this link http://www.whatismyscreenresolution.com/ on the retina ipad to see what is the reported screen resolution.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Even, when I created a book using the 1024 X 768 visual queues then looked at it on a iPad with Retina Display. It didn't display the whole height of the book correctly.

**Comment by LindsayThomas** [comment]
Go to http://50.18.115.76/BriefingBookSpring/  with the Book Name (iPad retina 1024 x 768) 

![screen shot 2015-03-19 at 5 16 27 pm](https://cloud.githubusercontent.com/assets/2379312/6758981/bd406340-cf12-11e4-99ae-cef8ebe292b8.png)

**Comment by LindsayThomas** [comment]
LT note: 1024 X 768 visual queues work for iPad Retina

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Can we discuss this issue on the call tomorrow? 

What I am really would like to talk about is the expectation what the resolution means?
