### ISSUE TITLE
Add the ability to Export to PDF

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#172]
Add the ability Export briefing book to PDF via the Viewing mode
-Static print is okay
-User only has the print option when in VIEW MODE of the application (You cannot export from author mode). 
-Icon is visible in VIEW MODE. Icon should be added between the HOME button and the CONTENTS button

(Closed #136 to open this issue)

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas As discussed during today's call, as we are not clear with the expectations for this enhancement, we are pushing the code with the implementation we had presented in the demo few weeks earlier.

Please review and let us know your expectations.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Thanks for summarizing. Once, I have accessed locally, I'll provide my feedback here.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam The print button and functionality is not present in the pull request. 
However, I did review on this URL: http://203.199.47.84/briefingbook/v2.0

The button place and UI are great for this feature. 
However, when you print the book using the default print function of the browser does not look good.
Can we export to a pdf or like format, with landscape mode, so all parts of the book are present? I realize that Firefox and Chrome default print functionality are unique however, printing using the browser does not produce a good book.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
We can confirm that print button and functionality is present in the pull request. Can you please confirm this?

About exporting to pdf, are you expecting the application to generate the pdf instead of the browser's 'save as pdf' as in chrome browser? This may lead to developing a separate server-side component as plain JavaScript cannot create pdf entirely on the client side.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam I can see print in the pull request (I thought I deleted that part of the comment)

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Added a new issue related to print functionality #198

**Comment by LindsayThomas** [comment]
Notes
tested IE9, Chrome, FF 
IE9\FF force portrait
Chrome allows landscape

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Can you provide any additional information about what is the level of effort would be as well as the technical implications for the user if we deployed some sort of server side printing?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
As discussed during the call last week, this involves a large amount of effort and may be considered in a future release.
