### ISSUE TITLE
After moving briefing book to subdir of my contents error while saving changes

### ISSUE THREAD

**Issue by mhovens** [Esri/briefing-book#180]
I created a briefing book. By default it is saved to my contents on our argis portal. I moved the file to a subdir of my contents. It opened fine but when I tried to save changes I got an error. When I moved the file back to the my contents it works as expected.

**Comment by LindsayThomas** [comment]
@mhovens 
This issue should be resolved in the up and coming release. 
The issue can be tracked here: #175
