### ISSUE TITLE
Pull v1.4 is displaying books differently than the last release version of BB. 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#183]
Pull v1.4 #181
Using the same book, in the v.1.4 application and the currently release version reveals that there is a difference in the way the book is displayed. (Testing the comparison was completed in the same browser, on the same machine at the same resolution).

In the code review, I didn't see anything that would indicate this would change. My concern is that maybe this pull request doesn't have the most up to date code from the original repo. Or maybe we missed a CSS reference somewhere. Please investigate. 

Comparison - Side by Side. Blue App is currently released version - Grey App is the v1.4 pull request
![alignmentissue](https://cloud.githubusercontent.com/assets/2379312/5710067/19ff9af4-9a6d-11e4-8d65-eddadeb3d2ab.png)

Blue App is currently released version - Scroll is NOT visible
![originalrelease1](https://cloud.githubusercontent.com/assets/2379312/5710196/0c010130-9a6e-11e4-9988-80a599cd2fda.png)

Grey App is the v1.4 pull request - Scroll is Visible
![v1 4release1](https://cloud.githubusercontent.com/assets/2379312/5710200/0ebaf19c-9a6e-11e4-9194-c20545edd516.png)

**Comment by CTLocalGovTeam** [comment]
While updating the pull request V1.4(Pull #181) to use 3.8 API instead of 3.10 API, a dojo's style resource is erroneously added to the default.htm page. This is the reason books appear different in V1.4 and V2.0. We have removed this resource from the default.htm and updated Pull #181.
