### ISSUE TITLE
When viewing BB on Android Tablet, cannot view in Portrait mode

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/briefing-book#185]
When showing the briefing book to a customer on an Android Tablet (ASUS Transformer T700), he accidentally roated the tablet to portrait mode, and got the error "App does not support this orientation".  This happened in both Chrome and the native Browser on the device.

I'm not sure if this is a bug or intended?

**Comment by LindsayThomas** [comment]
@kerryrobinson This is designed to function this way. Thanks for reporting.
