### ISSUE TITLE
Does the order of the config.js matter?

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#189]
As long as the items in the config.js are contained in the function

define([], function () {
    return {

Can I move around the items?  

I wanted to move the items lower in the list... 

       // Video URL for YouTube
        YouTubeVideoUrl: "https://www.youtube.com/embed/",

        // Video URL for Esri
        EsriVideoUrl: "https://video.esri.com/iframe/",

        // Video URL for Vimeo
        VimeoVideoUrl: "https://player.vimeo.com/video/",

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas  Yes these tags can be placed anywhere in config.

**Comment by LindsayThomas** [comment]
LT - updated the order
