### ISSUE TITLE
Question about when Alert message occurs?

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#190]
If the parameter  "DisplayBook"  "" is empty then the user will get the Alert 
"Alert - Please check your configuration"

This works correctly. Is this Alert message specific to the DisplayBook parameter or is the same Alert message displayed for other configuration errors? 

(Just want to know if we should make the message more specific or let it remain generic)

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas  If app gets failed due to any configuration error then the above message gets displayed.
