### ISSUE TITLE
Add Briefing Book as an ArcGIS Online web application template

### ISSUE THREAD

**Issue by jeffbaranyi** [Esri/briefing-book#192]
Can we add the Briefing Book as an ArcGIS Online web application template?  The requirement to host the web app on a server is inhibiting adoption.

**Comment by LindsayThomas** [comment]
@jeffbaranyi Can you provide more details of where this requirement is coming from. Please just email me directly.

**Comment by jeffbaranyi** [comment]
@LindsayThomas sounds good.  Let me know if you need more details beyond what I sent.

**Comment by LindsayThomas** [comment]
@jeffbaranyi Thanks Jeff. I added the information to our internal document.
