### ISSUE TITLE
IE9 and IE8 Viewing Only question

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#193]
It doesn’t seem like the currently delivered Briefing Book work on IE9 and IE8 for viewing only?

-We know that Authoring a Briefing Book Requires SSL on the web application server for IE8 and 9 

-“Viewing Only” a  Briefing Book didn’t originally require SSL to work for IE8 and IE9  (I believe this was only tested on V.1.0 of briefing book) 

Are there any concerns with fixing the appliation to support viewing of books in IE9 and IE8? (viewing only, I realize authoring requires SSL)

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas - We tested the application for the provided scenario and were able to access the books in view mode. Can you provide the steps to repro this issue?

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam I cannot reproduce this issue on a truly native IE9 browser. No action required. Thanks for quickly responding to this question.
