### ISSUE TITLE
If Summary Item Text of a webmap is empty. 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#194]
When the "Summary" of the webmap is not available then, the application displays "null" in Caption section of the application. 

Instead of returning "null" please return it empty. 

![nullinsummary](https://cloud.githubusercontent.com/assets/2379312/6527823/e879bcdc-c3eb-11e4-9ad5-1561eb88b7f7.png)

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas We will provide this fix in next release.

**Comment by LindsayThomas** [comment]
string is empty instead of null. 
updating an empty string persists. 
Verified
