### ISSUE TITLE
Portal Review 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#196]
@conklinbd Just Closed this once you portal review is finished. I just wanted to have it as an issue.

**Comment by conklinbd** [comment]
@LindsayThomas 
I deployed the app to our Portal. This is a 10.3.1 Portal with IWA. This also means that it is SSL only.
I replaced all the url references with the locally installed javascript api. I verified that no external calls are being made (Psuedo Disconnected Test). 

After doing that i tested creating and editing books. All layouts and standard widgets. I also tested the print widget and the new layout "hints" for the different device types.

Everything looks good to me. No issues to report.
