### ISSUE TITLE
UI elements show in Browser print preview but are not actually being printed.

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#199]
UI elements show in Browser print preview but are not actually being printed.

See Image below:
![missing](https://cloud.githubusercontent.com/assets/2379312/6813554/8f971c12-d24c-11e4-8389-4d8694fd7b1f.jpg)

@CTLocalGovTeam

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas Browser print dialog provides an option to print the background images. Could you please check if these images in the print after enabling 'Background Graphics’ option.

Below is the screenshot from chrome print dialog for your ready reference..
![bb172](https://cloud.githubusercontent.com/assets/2959186/6827195/132bb4a4-d32c-11e4-9c75-4bd246cee17c.png)

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam This works in Chrome.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
We are able to reproduce this issue. This is happening because in print preview mode, sometimes the legend does not hide properly. We have fixed it by appropriately setting the css 'display' property of legend container in print preview mode.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Great.

**Comment by LindsayThomas** [comment]
chrome tested\verified
