### ISSUE TITLE
Private Book do not populate a URL in the ArcGIS Online URL item

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#200]
Private Book do not populate a URL in the ArcGIS Online URL item/

Repro Steps
Create a book
Do not Share It
Save Book
Look at book as an AGOL Item. The URL field is empty.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas We internally found this issue and have already fixed this, We will provide the fix in next release.

**Comment by LindsayThomas** [comment]
Verified on 2.1 with dojo change.
