### ISSUE TITLE
Private Books created with DisplayBook set to group are not being created in the group by default. Therefore, when you sign in again you cannot see the book.

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#205]
Related to these two comments: https://github.com/Esri/briefing-book/issues/162#issuecomment-68867854 and
https://github.com/Esri/briefing-book/issues/162#issuecomment-68947766

(This was supposed to be fixed in #162. I opened this as a new issue because 162 has so much information in it. It is hard to track) 

Issue A:
Private Books created with DisplayBook set to group are not being created in the group by default. Therefore, when you sign in again you cannot see the book.

Repro Steps" 
-In AGOL create a group (Group is Private)
-Configure Briefing Book to DisplayBook 'group' (config groupid as well) 

-Open Application "Sign In"
-Create a new book and save it
-Sign out
-Sign in, again
-Book is not visible (Book is created but should be created into to the group even though it is private)

Issue B: 
Private Books moved into a private group being referenced by briefing book are not being displayed. 

Repro Steps" 
-In AGOL create a group (Group is Private)
-Configure Briefing Book to DisplayBook 'group' (config groupid as well) 

-Open Application "Sign In"
-Create a new book and save it
-Sign out
-In AGOL move the book, into the private group
-Sign in, again
-Book is not visible

Issue C: 
The scenario below needs to be supported as well. If we fix Issue A and B then I think this will happen naturally. 

organization1 has a private group . The private group has members from both organization1 and organization2 belonging to the group. When the ability in AGOL to share to the group from either organization1 or organization2.   (both organizations are organizational accounts)

When organization1user or organization2user are logged into the briefing book, then books will be created in the organization they belong to, but will be shared to the shared private group in organization1. (briefing book is configured to point to display item group and use portal URL argis.com).

This is an EM requirement. 

@CTLocalGovTeam

**Comment by LindsayThomas** [comment]
The scenario above needs to be supported, as well as, the scenario below: 

organization1 has a private group . The private group has members from both organization1 and organization2 belonging to the group. When the ability in AGOL to share to the group from either organization1 or organization2.   (both organizations are organizational accounts)

When organization1user or organization2user are logged into the briefing book, then books will be created in the organization they belong to, but will be shared to the shared private group in organization1. (briefing book is configured to point to display item group and use portal URL argis.com),

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 

1. Issue A: We are able to repro this. 
  * this is because of asynchronous requests for adding, updating and sharing the book on AGOL. This can be fixed by sending the requests in synchronous order.
2. Issue B: We are not able to repro this. Will investigate this further.
3. Issue C: We are able to repro this. If issue A is fixed then, this issue will also be resolved.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas, We are still unable to repro Issue B with the code that was delivered in last drop.
Here is a test deployment where we are able to see books created in a private group.

Please follow the steps below.
1. Open app http://203.199.47.84/briefingbook/test205/ 
2. Login with valid credentials for https://arcgis4localgov2.maps.arcgis.com/
3. Create a new book and save it
4. Sign out of the app
5. In AGOL share the book, into the private group 'LG_BriefingBooks'
6. Sign in again into the app
7. Notice that book is visible

Can you please confirm if you can repro this.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam I am not seeing issue B anymore.

**Comment by LindsayThomas** [comment]
Verified
