### ISSUE TITLE
Searching for Webmap is not searching tags 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#207]
Searching for Webmap in the webmap module is not searching the tags of the items

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
Currently, the webmap search functionality is designed to search webmaps by their title. We can change this to search by title + tags. However, we see that,  while searching items in ArcGIS Online, it matches the search term with title ,tags, description and other attributes of the item also. If search term is found in any of item attributes, it is shown in search results.

Would you like us to implement search using title + tags or as implemented in ArcGIS Online? 
Implementing AGOL like search is also a minor code change.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Please Search all AGOL items. Please ensure that priority is established for this. Priority should be Title, Tag, Summary, description, and other items.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas, we cannot set priority of searching through title, tag, summary and description as the API does not provide means to achieve this.

The current implementation of searching is (when search term is 'mapbooks')
[http://www.arcgis.com/sharing/rest/search?num=100&start=1&sortField=title&sortOrder=asc& q=title:mapbooks AND type:"Web Map" -type:"Web Mapping Application"&f=pjson](http://www.arcgis.com/sharing/rest/search?num=100&start=1&sortField=title&sortOrder=asc&q=title:mapbooks AND type:"Web Map" -type:"Web Mapping Application"&f=pjson)
This returns 8 results as it searches only in item titles. Notice `q=title:mapbooks`

We could either do 

1. `q=title:mapbooks OR tags:mapbooks` which returns 10 results. 
[http://www.arcgis.com/sharing/rest/search?num=100&start=1&sortField=title&sortOrder=asc&q= title:mapbooks OR  tags:mapbooks AND type:"Web Map" -type:"Web Mapping Application"&f=pjson](http://www.arcgis.com/sharing/rest/search?num=100&start=1&sortField=title&sortOrder=asc&q= title:mapbooks OR tags:mapbooks AND type:"Web Map" -type:"Web Mapping Application"&f=pjson)

2. OR, we could just do `q=mapbooks` which returns 24 results like this
[http://www.arcgis.com/sharing/rest/search?num=100&start=1&sortField=title&sortOrder=asc& q=mapbooks AND type:"Web Map" -type:"Web Mapping Application"&f=pjson](http://www.arcgis.com/sharing/rest/search?num=100&start=1&sortField=title&sortOrder=asc&q=mapbooks AND type:"Web Map" -type:"Web Mapping Application"&f=pjson)

Please let us know which option you would like us to implement.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Instead, please search for title, tag, summary and description.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas Ok. Thanks for the confirmation.

We will use the following query to look for search term in title, tags, summary and description.

[http://www.arcgis.com/sharing/rest/search?num=100&start=1&sortField=title&sortOrder=asc&q=(title:mapbooks OR tags:mapbooks OR snippet:mapbooks OR description:mapbooks) AND type:"Web Map" -type:"Web Mapping Application"&f=pjson](http://www.arcgis.com/sharing/rest/search?num=100&start=1&sortField=title&sortOrder=asc&q=(title:mapbooks OR tags:mapbooks OR snippet:mapbooks OR description:mapbooks) AND type:"Web Map" -type:"Web Mapping Application"&f=pjson)

**Comment by LindsayThomas** [comment]
Tag works
