### ISSUE TITLE
The ability to create new books is disabled when no books are returned the author mode is false. 

### ISSUE THREAD

**Issue by conklinbd** [Esri/briefing-book#41]
When logging in to a portal I do not get the option to create a new book. There are no obvious errors returned and the page loads normally.

My impression is that this issue is caused by the fact that the Portal does not have any books loaded initially. I am manually creating a book on the Portal and will test to verify that this is the root cause.

**Comment by nfeuerstein** [comment]
Installed v1.4 on new developmental portal (no books) and it seems this issue has reappeared: https://nsec.esri.com/SolutionsWeb/Apps/NationalIntel/BriefingBook/

**Comment by LindsayThomas** [comment]
@nfeuerstein We actually did a bigger fix on this in the other pull. It is strange that is seems to have bounced. Are you able to test in portal on this build and let us know if the issue still exists. 

The true\false setting is now active. False will not allow authoring and True will.
https://github.com/Esri/briefing-book/tree/develop_2.0

**Comment by conklinbd** [comment]
@LindsayThomas I deployed an updated version and it works. Thanks.
