### ISSUE TITLE
Module string needs to be update. Edit Webmap should be Edit Map

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/briefing-book#94]
Repro
In Authoring Mode add or edit a map. 
The UI says "Edit Webmap"
Please change "Edit Webmap" to say "Edit Map" 

Also, this string should be part of the localizedstring.js file

**Comment by LindsayThomas** [comment]
UI has been updated to day Edit Map. 
However, the word Edit seems be hard coded. Please add the whole phase "Edit Map" to the  localized_string.js

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas Currently "Edit" text in setting dialog is configured in localized-strings.js with the following tag-
settingDialogTitle: "Edit ${modType}",
where modType will be replaced by the module type.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Thanks for clarifying. No further action required.
